package main

import (
	"context"
	"fmt"
	"os"

	"gitlab.com/smoothsics/ainp/internal/equity"
	"gitlab.com/smoothsics/ainp/internal/poker"
)

const samplesPerClass = 20_000

func main() {
	calculator := equity.NewCalculator()
	fmt.Println("// Code generated by cmd/preflopgen; DO NOT EDIT.")
	fmt.Println("package equity")
	fmt.Println()
	fmt.Println("var preflopHeadsUpRandom = map[string]PreflopEntry{")
	for high := 14; high >= 2; high-- {
		for low := high; low >= 2; low-- {
			variants := []bool{false}
			if high != low {
				variants = []bool{true, false}
			}
			for _, suited := range variants {
				hero := startingCards(high, low, suited)
				key, _ := equity.StartingHandClass(hero)
				result, err := calculator.Calculate(context.Background(), equity.Request{
					Hero: hero, Opponents: [][]poker.Card{{}}, Algorithm: equity.AlgorithmMonteCarlo,
					Samples: samplesPerClass, Seed: int64(high*10_000 + low*100 + boolInt(suited)),
				})
				if err != nil {
					fmt.Fprintln(os.Stderr, err)
					os.Exit(1)
				}
				fmt.Printf("\t%q: {WinProbability: %.8f, TieProbability: %.8f, Equity: %.8f, Trials: %d},\n", key, result.WinProbability, result.TieProbability, result.Equity, result.Trials)
			}
		}
	}
	fmt.Println("}")
}

func startingCards(high, low int, suited bool) []poker.Card {
	first, _ := poker.NewCard(high, 's')
	secondSuit := byte('h')
	if suited {
		secondSuit = 's'
	}
	second, _ := poker.NewCard(low, secondSuit)
	return []poker.Card{first, second}
}

func boolInt(value bool) int {
	if value {
		return 1
	}
	return 0
}
